---
- name: GATHER OS SPECIFIC VARS
  include_vars: "{{ item }}"
  with_first_found:
    - "../../../vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "../../../vars/{{ ansible_distribution }}.yml"
    - "../../../vars/{{ ansible_os_family }}.yml"

- include: centos.yml
  when: ansible_distribution == "CentOS"

- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: NTPD | START SERVICE
  service: name={{ ntp_service }} state=started enabled=yes

- name: NTPD | SYNC TIME
  command: ntpdate -u 0.pool.ntp.org 1.pool.ntp.org 2.pool.ntp.org 3.pool.ntp.org
